[server]
port = 2080
address = "127.0.0.1"
headless = true

[browser] # This ip and port will show in command prompt
serverAddress = "59676837.xyz" # Put your Local IP or Domain Name
serverPort = 2080

[theme]
primaryColor="#F63366"
backgroundColor="#FFFFFF"
secondaryBackgroundColor="#F0F2F6"
textColor="#262730"
font="sans serif"
